[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "olympoly"
version = "0.1.0"
description = "Olympics data analysis."
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "datasets>=4.8.4",
    "numpy>=2.0",
    "pandas>=2.2",
    "seaborn>=0.13",
    "scikit-learn>=1.8.0",
    "python-dotenv>=1.0.0",
    "requests>=2.31.0",
    "matplotlib>=3.8.0",
]

[project.optional-dependencies]
dev = [
    "pytest",      
    "jupyter", 
    "ruff",       
]